version: "3.3"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    network_mode: host
    restart: unless-stopped
    command: python -m uvicorn main:app --host 0.0.0.0 --port 7777
    env_file:
      - .env
    volumes:
      - /bsc_mukhin/db.sqlite:/zoom/db.sqlite
